config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  devise_for :users
  root 'file_managers#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  get '/create' => 'file_managers#create'
  post '/create' => 'file_managers#create'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  def uploaded_file=(incoming_file)
    self.filename = incoming_file.original_filename
    self.content_type = incoming_file.content_type
    self.data = incoming_file.read
  end

  def filename=(new_filename)
    write_attribute("filename", sanitize_filename(new_filename))
  end

  private
  def sanitize_filename(filename)
    #get only the filename, not the whole path (from IE)
    just_filename = File.basename(filename)
    #replace all non-alphanumeric, underscore or periods with underscores
    just_filename.gsub(/[^\w\.\-]/, '_')
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profiles
end

app/models/user_observer.rb
class UserObserver< ActiveRecord::Observer
  def after_save(record)
    record.logger.info("####################")
    record.logger.info("+++ CustomerObserver:
The customer #{record.user_name} was added with ID #{record.id}")
    record.logger.info("####################")

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    "/signedinuserprofile"
  end

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_name, :email, :password, :current_password) }
        end
end

app/controllers/file_managers_controller.rb
class FileManagersController < ApplicationController
  def index
  #  render :file => '/app/views/file_managers/upload.html.erb'
  end

  def create
    @filename_n_wordcount = []
    @records = Dir.glob("public/files/*")
    if request.post?
# gets file input from the user
      uploaded_io_arr = []
      uploaded_io_arr << params[:query]
      uploaded_io_arr << params[:file2]
      uploaded_io_arr << params[:file3]
      uploaded_io_arr << params[:file4]
      uploaded_io_arr << params[:file5]
      uploaded_io_arr << params[:file6]
      uploaded_io_arr << params[:file7]
      filename_arr = []
      doc_num = uploaded_io_arr.compact!.size
# This saves the file to the public folder
      uploaded_io_arr.each do |value|
        File.open(Rails.root.join('public', 'files', value.original_filename), 'wb') do |file|
          file.write(value.read)
          filename_arr << value.original_filename            # to arr of original file names e.g VM Level Load Balancing in Cloud Environment.pdf
        end

# This gets the file of the same name from the public folder
        filename_arr.each do |each_filename|                 #goes through each file name
          file_handle = File.expand_path(Rails.root.join('public', 'files',each_filename)) # searches public folder for each file name
          page_text = []
          PDF::Reader.open(file_handle) do |reader|        # Reads pdf, and extract the text
            reader.pages.each do |page|
              page_text << page.text
            end
          end
          doc_text = page_text.join(' ')
          hash = {:key => each_filename, :value => doc_text}

# This gets the word counts of chosen documents e.g Cloud => 4, the => 89, christmas => 1
          document1 = TfIdfSimilarity::Document.new(hash[:value])
          term_n_counts = document1.term_counts
          @data = {:key => each_filename, :value => term_n_counts}
        end
        @filename_n_wordcount << @data
      end
#files are deleted after data have been extracted from pdf
      uploaded_io_arr.each do |value|
        File.delete(Rails.root.join('public', 'files', value.original_filename))
      end
      self.find_similarity(@filename_n_wordcount, doc_num)
    end
  end

  def find_similarity(filename_n_wordcount ,doc_num)
    get = Tf_idf_hash.new(filename_n_wordcount, doc_num)
    @tf_idf = 	get.tf_idf(get.tf, get.idf)
    first_file = @tf_idf.to_a
    query = Hash[*first_file[0]]

    cos_gem = Cosine_similarity_hash.new
    @cosine = cos_gem.cosine_sim(@tf_idf , query)

    @result = @cosine.keys
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def signedinuserprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to "/profiles/new"
    else
      @profile = Profile.find_by_user_id(current_user.id)
      redirect_to "/profiles/#{@profile.id}"
    end
  end


  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    @profile.user_id = current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end


  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
#after_sign_in_path_for is called by devise
  def after_sign_in_path_for(user)
    "/signedinuserprofile" #here we provide
#the path for the user’s profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_managers_helper.rb
module FileManagersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/file_managers/create.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<style>

    text {
        font: 10px sans-serif;
    }

</style>
<body>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

    var diameter = 960,
            format = d3.format(",d"),
            color = d3.scale.category20c();

    var bubble = d3.layout.pack()
            .sort(null)
            .size([diameter, diameter])
            .padding(1.5);

    var svg = d3.select("body").append("svg")
            .attr("width", diameter)
            .attr("height", diameter)
            .attr("class", "bubble");

    d3.json("flare.json", function(error, root) {
        var node = svg.selectAll(".node")
                .data(bubble.nodes(classes(root))
                        .filter(function(d) { return !d.children; }))
                .enter().append("g")
                .attr("class", "node")
                .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });

        node.append("title")
                .text(function(d) { return d.className + ": " + format(d.value); });

        node.append("circle")
                .attr("r", function(d) { return d.r; })
                .style("fill", function(d) { return color(d.packageName); });

        node.append("text")
                .attr("dy", ".3em")
                .style("text-anchor", "middle")
                .text(function(d) { return d.className.substring(0, d.r / 3); });
    });

    // Returns a flattened hierarchy containing all leaf nodes under the root.
    function classes(root) {
        var classes = [];

        function recurse(name, node) {
            if (node.children) node.children.forEach(function(child) { recurse(node.name, child); });
            else classes.push({packageName: name, className: node.name, value: node.size});
        }

        recurse(null, root);
        return {children: classes};
    }

    d3.select(self.frameElement).style("height", diameter + "px");

</script>

app/views/file_managers/index.html.erb
<%if current_user %>
    <center><h1>ReHub</h1></center>
    <br>
    <br>
    <%= form_tag 'create' , :multipart => true do %>
        <center><h4>Please upload your query document:</h4></center>
        <center><%= file_field_tag 'query' %></center>

        <center><h4>Please upload the files you want to compare the query with:</h4></center>
        <center><%= file_field_tag 'file2' %></center>
        <center><%= file_field_tag 'file3' %></center>
        <center><%= file_field_tag 'file4' %></center>
        <center><%= file_field_tag 'file5' %></center>
        <center><%= file_field_tag 'file6' %></center>
        <center><%= file_field_tag 'file7' %></center>
        <br>
        <center><%= submit_tag "Send Attachment" %></center>
    <% end %>
    <br>
    <center><%= flash[:notice] %></center>
    <%= flash[:error] %>c
    <br>
    <br>

    <center><h2>View your recent comparisons:</h2></center>
    <%= form_tag 'show' , :multipart => true do %>
        <center> <%= submit_tag "Show" %></center>
    <% end %>
    <br>
    <%else%>
    <%= render :file => 'app/views/file_managers/upload.html.erb'%>
<%end%>

app/views/file_managers/show.html.erb
<br>
<%= form_tag("/show", method: "choose_files") do %>
    <%= label_tag(:id, "Search PDF ID:") %>
    <%= text_field_tag(:id) %>
    <%= submit_tag("Search") %>
<% end %>
<br>

<%= form_tag 'create' , :multipart => true do %>
    <%= submit_tag "Back to upload" %>
<% end %>
<h1>===========Choose files to be analysed=================</h1>


<% if @f.present? %>
    <%= form_tag({action: :display_show}, multipart: true, name: 'file') do %>
        <% @f.each do |chk| %>
        <br>

        <%=check_box_tag "[file][#{chk}]",chk %>
        <%=chk %> <br/>
    <% end %>
    <%= submit_tag("Analyze") %>
<% end %>
<% end  %>
<br>
<h1>==============Output==================</h1>

<%=@fr%>
<h1>========================================</h1>

<h2>Database list:</h2>
<h3>ID   |  Filename</h3>
<% Attachment.all.each do |user| %>
    <p>
    <b><%= user.id %></b>  |  <%= user.filename %>
    </p>
<% end %>
<br>

app/views/file_managers/upload.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <title>Rehub</title>
</head>
<body>
<div id='header'>
  <!-- Header Image Displayes here -->
</div>
<!--<div id='menu'>
  <div id="navbar">
    <ul>
      <li><a href="/customers">Customers</a></li>
    </ul>
  </div>
</div>-->
<div id='container'>
  <div id='content'>
    <p class="notice"><%= flash[:notice] %></p>
    <%= yield %>
  </div>
 <center>
  <div id='first-column'>
    <div class="loginbox">
      <% if user_signed_in? %>
          <h2 class="BoxHeaders">Signed in as... <%= current_user.email %>
            (<%= link_to 'Sign out', destroy_user_session_path,
          :method => :delete%>)
          </h2>
      <% else %>
          <h2 class="BoxHeaders"> <%= link_to 'Register', new_user_registration_path %> </h2>
          <h2 class="BoxHeaders"> <%= link_to 'Sign in', new_user_session_path %> </h2>
      <% end %>
    </div>
<!--    <div class="searchbox">
      <h2 class="BoxHeaders">Search...</h2>
    </div>-->
  </div>
  </center>
</div>
<!--<div id='footer'>
  <h6 class="footertext">&copy; ReHub Application &trade; 2014</h6>
</div>-->
</body>
</html>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "ReHub", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            	<li class="title-3">Welcome, <%= current_user.user_name %></li>

                <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Login', new_user_session_path %></li>
                <li><%= link_to 'Register', new_user_registration_path %></li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReHub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/flash_messages' %>
<%= render 'layouts/menu' %>

<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>